#pragma once
// generated by wordring_cpp/generator/whatwg/encoding/encoding.cpp

#include <array>
#include <map>
#include <vector>

namespace wordring::whatwg::encoding
{
	extern std::vector<uint32_t> const index_code_point_big5; // 19782
	extern std::vector<uint32_t> const index_code_point_euc_kr; // 23940
	extern std::array<uint32_t, 23940> const index_code_point_gb18030; // 23940
	extern std::vector<uint32_t> const index_code_point_jis0208; // 11280
	extern std::vector<uint32_t> const index_code_point_jis0212; // 8836
	extern std::vector<uint32_t> const index_code_point_ibm866; // 128
	extern std::vector<uint32_t> const index_code_point_iso_2022_jp_katakana; // 63
	extern std::vector<uint32_t> const index_code_point_iso_8859_2; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_3; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_4; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_5; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_6; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_7; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_8; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_10; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_13; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_14; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_15; // 128
	extern std::vector<uint32_t> const index_code_point_iso_8859_16; // 128
	extern std::vector<uint32_t> const index_code_point_koi8_r; // 128
	extern std::vector<uint32_t> const index_code_point_koi8_u; // 128
	extern std::vector<uint32_t> const index_code_point_macintosh; // 128
	extern std::vector<uint32_t> const index_code_point_windows_874; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1250; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1251; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1252; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1253; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1254; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1255; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1256; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1257; // 128
	extern std::vector<uint32_t> const index_code_point_windows_1258; // 128
	extern std::vector<uint32_t> const index_code_point_x_mac_cyrillic; // 128

	extern std::multimap<uint32_t, uint32_t> const index_code_point_gb18030_ranges; // 207

	extern std::vector<uint32_t> const index_pointer_big5_0; //14659
	extern std::vector<uint16_t> const index_pointer_big5_1; //14659
	extern std::vector<uint32_t> const index_pointer_euc_kr_0; //17048
	extern std::vector<uint16_t> const index_pointer_euc_kr_1; //17048
	extern std::vector<uint32_t> const index_pointer_gb18030_0; //23939
	extern std::vector<uint16_t> const index_pointer_gb18030_1; //23939
	extern std::vector<uint32_t> const index_pointer_jis0208_0; //7326
	extern std::vector<uint16_t> const index_pointer_jis0208_1; //7326
	extern std::vector<uint32_t> const index_pointer_jis0212_0; //6067
	extern std::vector<uint16_t> const index_pointer_jis0212_1; //6067
	extern std::vector<uint32_t> const index_pointer_ibm866_0; //128
	extern std::vector<uint16_t> const index_pointer_ibm866_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_2022_jp_katakana_0; //63
	extern std::vector<uint16_t> const index_pointer_iso_2022_jp_katakana_1; //63
	extern std::vector<uint32_t> const index_pointer_iso_8859_2_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_2_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_3_0; //121
	extern std::vector<uint16_t> const index_pointer_iso_8859_3_1; //121
	extern std::vector<uint32_t> const index_pointer_iso_8859_4_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_4_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_5_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_5_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_6_0; //83
	extern std::vector<uint16_t> const index_pointer_iso_8859_6_1; //83
	extern std::vector<uint32_t> const index_pointer_iso_8859_7_0; //125
	extern std::vector<uint16_t> const index_pointer_iso_8859_7_1; //125
	extern std::vector<uint32_t> const index_pointer_iso_8859_8_0; //92
	extern std::vector<uint16_t> const index_pointer_iso_8859_8_1; //92
	extern std::vector<uint32_t> const index_pointer_iso_8859_10_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_10_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_13_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_13_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_14_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_14_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_15_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_15_1; //128
	extern std::vector<uint32_t> const index_pointer_iso_8859_16_0; //128
	extern std::vector<uint16_t> const index_pointer_iso_8859_16_1; //128
	extern std::vector<uint32_t> const index_pointer_koi8_r_0; //128
	extern std::vector<uint16_t> const index_pointer_koi8_r_1; //128
	extern std::vector<uint32_t> const index_pointer_koi8_u_0; //128
	extern std::vector<uint16_t> const index_pointer_koi8_u_1; //128
	extern std::vector<uint32_t> const index_pointer_macintosh_0; //128
	extern std::vector<uint16_t> const index_pointer_macintosh_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_874_0; //120
	extern std::vector<uint16_t> const index_pointer_windows_874_1; //120
	extern std::vector<uint32_t> const index_pointer_windows_1250_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1250_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_1251_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1251_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_1252_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1252_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_1253_0; //125
	extern std::vector<uint16_t> const index_pointer_windows_1253_1; //125
	extern std::vector<uint32_t> const index_pointer_windows_1254_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1254_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_1255_0; //118
	extern std::vector<uint16_t> const index_pointer_windows_1255_1; //118
	extern std::vector<uint32_t> const index_pointer_windows_1256_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1256_1; //128
	extern std::vector<uint32_t> const index_pointer_windows_1257_0; //126
	extern std::vector<uint16_t> const index_pointer_windows_1257_1; //126
	extern std::vector<uint32_t> const index_pointer_windows_1258_0; //128
	extern std::vector<uint16_t> const index_pointer_windows_1258_1; //128
	extern std::vector<uint32_t> const index_pointer_x_mac_cyrillic_0; //128
	extern std::vector<uint16_t> const index_pointer_x_mac_cyrillic_1; //128

	extern std::multimap<uint32_t, uint32_t> const index_pointer_gb18030_ranges; // 207

	extern std::vector<uint32_t> const index_pointer_Shift_JIS_0;
	extern std::vector<uint16_t> const index_pointer_Shift_JIS_1;
}

