#pragma once
// generated by wordring_cpp/generator/whatwg/html/atom_tbl.cpp

#include <cstdint>

namespace wordring::whatwg::html::parsing
{
	enum class namespaces : std::uint32_t
	{
		HTML = 3040,
		MathML = 3012,
		SVG = 3085,
		XLink = 3054,
		XML = 3178,
		XMLNS = 3108,
	};
}
